name: Architecture checking prototype

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r .scripts/requirements.txt || true

      - name: Run architecture check
        run: python .scripts/main.py
